# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8453002bd9de628fb7c661afb02b37f1445a28ec5ce85ac51a07ebc94b4b53e854a41636a2ecd21a83794419eb46c546952119dd1be827f8abc718856ba5127

test:
  secret_key_base: 8dfbab90449f1c54eb4204c232941524476e505efb07d871862ca6bd4e013902c4f1345b8ad62e7a4fc29cd5f70e3c159c9e84c0184cdacda1c2a34fd6aca170

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
